### ISSUE TITLE
Login attempt exceeds character limit

### ISSUE THREAD

**Issue by Eayyu20** [Pierre120/jack-frost-premium#26]
Users can still physically input emails and passwords that exceed the character limit.

The user should not have the ability to input emails and passwords that exceed 32 and 20 characters respectively. When the user types a character over the limit, the input text field refuses the input and the screen does not update with the exceeded character/s.

![Screenshot 2023-03-07 161213](https://user-images.githubusercontent.com/94160469/223362762-0778960d-9e5a-4fa7-ac08-4c85ee4dd817.jpg)

**Comment by Pierre120** [comment]
This issue has been patched in this PR #21
